-- SQL Script for Supabase setup

-- Create "products" table
CREATE TABLE public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name_ar TEXT NOT NULL,
  name_en TEXT NOT NULL,
  desc_ar TEXT,
  desc_en TEXT,
  category TEXT NOT NULL,
  price NUMERIC NOT NULL,
  weight_ar TEXT NOT NULL,
  weight_en TEXT NOT NULL,
  image_url TEXT NOT NULL,
  badge_ar TEXT,
  badge_en TEXT,
  bg_color TEXT NOT NULL DEFAULT 'bg-cream',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create "orders" table
CREATE TABLE public.orders (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items JSONB NOT NULL,
  total_price NUMERIC NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Turn on row level security
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow public read access to products
CREATE POLICY "Public profiles are viewable by everyone."
  ON public.products FOR SELECT
  USING (true);

-- Allow public inserts to orders
CREATE POLICY "Public users can insert their own orders."
  ON public.orders FOR INSERT
  WITH CHECK (true);

-- Insert premium bilingual products
INSERT INTO public.products (name_ar, name_en, desc_ar, desc_en, category, price, weight_ar, weight_en, badge_ar, badge_en, image_url, bg_color) VALUES
('تونة بيضاء فاخرة (قطع صلبة)', 'Premium White Tuna (Solid)', 'تونة بيضاء فاخرة بقطع صلبة غنية بالأوميغا 3، مثالية للسلطات والوجبات الصحية.', 'Premium solid white tuna rich in Omega-3, perfect for salads and healthy meals.', 'Tuna', 35, '٢٠٠ غرام', '200g', 'غني بالأوميغا 3', 'Rich in Omega 3', 'https://images.unsplash.com/photo-1590412200988-a436970781fa?auto=format&fit=crop&w=800&q=80', 'bg-blue-50'),
('صلصة طماطم عضوية', 'Organic Tomato Sauce', 'صلصة طماطم عضوية مصنوعة من مكونات طبيعية بدون سكر مضاف.', 'Organic tomato sauce crafted from natural ingredients with no added sugar.', 'Sauces', 25, '٥٠٠ غرام', '500g', 'بدون سكر مضاف', 'No Added Sugar', 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=800&q=80', 'bg-red-50'),
('سمن مزرعة أصيل', 'Authentic Farm Ghee', 'سمن طبيعي ١٠٠٪ من مزارع محلية، غني بالنكهة الأصيلة والفوائد الغذائية.', '100% natural farm ghee with authentic flavor and rich nutritional benefits.', 'Ghee', 120, '١ كجم', '1kg', 'طبيعي ١٠٠٪', '100% Natural', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=800&q=80', 'bg-yellow-50'),
('زيت زيتون بكر ممتاز', 'Extra Virgin Olive Oil', 'زيت زيتون بكر ممتاز معصور على البارد، مثالي للطهي الفاخر والسلطات.', 'Cold-pressed extra virgin olive oil, ideal for luxury cooking and salads.', 'Organics', 85, '٥٠٠ مل', '500ml', 'عصرة باردة', 'Cold Pressed', 'https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?auto=format&fit=crop&w=800&q=80', 'bg-green-50'),
('تونة لحم خفيف (رقائق)', 'Light Meat Tuna (Chunks)', 'تونة لحم خفيف بقطع رقيقة، خيار مثالي لمن يبحث عن وجبة قليلة السعرات.', 'Light meat tuna chunks, the perfect low-calorie choice for mindful eating.', 'Tuna', 20, '١٨٥ غرام', '185g', 'قليل السعرات', 'Low Calorie', 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80', 'bg-cyan-50'),
('عسل جبلي خام', 'Raw Mountain Honey', 'عسل جبلي خام غير مصفى، يحتفظ بجميع إنزيماته وفوائده الطبيعية.', 'Unfiltered raw mountain honey preserving all natural enzymes and benefits.', 'Organics', 150, '٥٠٠ غرام', '500g', 'غير مصفى', 'Unfiltered', 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80', 'bg-amber-50');
